### PR TITLE
Close #13. Display message after entity consumes food item

### LINKED ISSUE #13: Helpful text after eating food
The amount of HP recovered should be nicely displayed after the entity eats some food.

A good formatting will display (1) the entity's name, (2) the food's name, and (3) the amount of HP recovered, such as: "Player1 uses Donut and recovers 7 HP!"

Additionally, the next line might show the current HP (divided by max HP) as: "HP: 92.5/100"

Other formats are also acceptable.

### PR DESCRIPTION
**Pull request by ryanflach**
- Add test to confirm message text
- Add method in entity.rb to produce dynamic message
- Add condition in use_item_by_string within entity to ensure message is displayed only on consumption of a food item

### CODE REVIEW

**Comment by ryanflach** [comment]
@nskins In order for the message to display only when a food item is consumed, I'm first checking that the `actual_item` is of type `Food`. `consumable` would be more appropriate from a readability standpoint, but the way `consumable` is implemented within the Item class leads any item without that param to be set to true, meaning that a non-food item could also produce the message. SimpleDelegator may be more appropriate to use, in place of inheritance, in the classes that currently inherit from `Item`.

**Comment by nskins** [comment]
@ryanflach This solution will not be robust since it places the effects of an item within the functions of the entity (imagine how cluttered it would become if more messages were necessary for future Item subclasses!)

Instead, the text from 'food_effects' can be printed directly from Food's 'use' function. This removes the need to check for the type (which is almost always a good thing - one less dependency). You should also move your test to spec/food_spec.rb.

In addition, you will need to account for the case when, say, the player (HP: 7/10) eats a Donut (recovers 5 HP). In this case, the output must specify that there is 3 HP recovered.

Thanks for the work so far! Let me know if you have questions. I will merge after you've made these changes.

**Comment by ryanflach** [comment]
@nskins Great notes. I'll try to make those changes tomorrow morning.

**Comment by ryanflach** [comment]
@nskins Made the changes you proposed. Let me know if anything still looks out of place.

**Pull request merged**
