### PR TITLE
adding gemfile to scaffold issue #127

### PR DESCRIPTION
**Pull request by virtual-monk**

### CODE REVIEW

**Comment by nskins** [comment]
Hi @virtual-monk. Please change the version back to 0.2.0 - I will change the version once I feel the release is all set to go. Everything else looks good. I will test on my machine after you've changed that. Thanks!

**Comment by virtual-monk** [comment]
Hey @nskins I made that change

**Comment by nskins** [comment]
@virtual-monk Please also capitalize the name of the source Gemfile. Sorry about all these minor revisions. I think that's everything...

**Comment by virtual-monk** [comment]
@nskins no worries, I pushed up those changes

**Comment by nskins** [comment]
Everything looks good. Thanks @virtual-monk!

**Pull request merged**
