### PR TITLE
Add text showing the player has left the shop.

### PR DESCRIPTION
**Pull request by silvestrijonathan**
Issue #14 

The text 
```ruby
"#{player.name} has left #{@name}"
```
Will now display at any time when the player leaves the shop.

All tests pass!

### CODE REVIEW

**Comment by nskins** [comment]
@silvestrijonathan Hey, there are a few minor style changes I am hoping you could make to your code.

- [ ] Your conditional check for printing the message is redundant since the input must be 'exit' to leave the main shop run loop. Thus, you should be able to remove the if statement that you added.

- [ ] We like to add an extra newline to make output look nice (especially when the next line requires input). Thus, change 'puts' to 'print', and then add two newlines to the end of the string (similar examples are elsewhere in shop.rb).

Let me know if you have questions.

**Comment by silvestrijonathan** [comment]
Simple enough changes, @nskins. When I get a moment, I'll go and add those in for you.

**Comment by silvestrijonathan** [comment]
@nskins, had a little trouble with my local branch-not sure what happened, but I'm just going to re-open a new PR with your recommendations.

**Comment by silvestrijonathan** [comment]
@nskins Had a small merge conflict that was causing some issues, but code now matches your specifications!

**Comment by nskins** [comment]
@silvestrijonathan That's fine. Thank you!!

**Comment by silvestrijonathan** [comment]
@nskins No problem!

**Pull request merged**
