### PR TITLE
Add NPC#say and tests

### PR DESCRIPTION
**Pull request by jamesball27**
Resolve issue #112

### CODE REVIEW

**Comment by nskins** [comment]
@jamesball27 - Cool! This looks good. However, please remove your second commit from this pull so that I can consider these features separately. I see that you've made a pull request for the other feature so I'll check that out shortly.

**Comment by jamesball27** [comment]
Sorry about that! I just removed the other commit.

**Comment by nskins** [comment]
Thanks. Sorry to be picky, but could you send the pull request from a different branch (not `master`). Your `master` branch should be the same as mine (origin/base) and I don't want anything funky happening if my `master` changes before we merge this.

**Comment by nskins** [comment]
Hi @jamesball27. You currently have three open pull requests with requested changes on each. Are you still working? If so, let's stick to one issue at a time. I'd like to merge this one first, then #115, then #118. Please let me know if you are still willing to make the changes. If not, I will re-open the issues.

**Comment by jamesball27** [comment]
Sorry for the delay, I just sent a new PR from a separate branch in #119

**Pull request merged**
